### Consulta de asistencias
GET http://api.asistenciasexto/asistencias

### Consulta de asistencia por id
GET http://api.asistenciasexto/asistencias/1

### Modificar Asistencia
PUT http://api.asistenciasexto/asistencias/1
Content-Type: application/json

{
  "cod_estudiante":1,
  "cod_asignacion":1,
  "cod_usuario_registro":2,
  "fecha":"2026-02-23",
  "estado":"Presente",
  "observacion":"Llegó puntual"
}

### Adicionar Asistencia
POST http://api.asistenciasexto/asistencias
Content-Type: application/json

{
  "cod_estudiante":2,
  "cod_asignacion":1,
  "cod_usuario_registro":1,
  "fecha":"2025-03-02",
  "estado":"Ausente",
  "observacion":"Falta injustificada"
}

### Eliminar Asistencia
DELETE http://api.asistenciasexto/asistencias/1
