### Consulta de docentes
GET http://api.asistenciasexto/docentes

### Consulta de docente por id
GET http://api.asistenciasexto/docentes/1

### Modificar Docente
PUT http://api.asistenciasexto/docentes
Content-Type: application/json

{
  "CI":"4567890",
  "nombre":"Maria",
  "apellido":"Quispe",
  "telefono":"70022222"
}

### Adicionar Docente
POST http://api.asistenciasexto/docentes
Content-Type: application/json

{
  "CI":"9876543",
  "nombre":"Carlos",
  "apellido":"Mamani",
  "telefono":"70033333"
}

### Eliminar Docente
DELETE http://api.asistenciasexto/docentes/1
