### Consulta de productos
GET http://api.asistenciasexto/productos

### Modificar Productos
PUT http://api.asistenciasexto/productos/1
Content-Type: application/json

{
  "codBarras":"750105531001",
  "descripcion":"Arroz Integral 3kg",
  "stock":50,
  "precio_unitario":12.50,
  "fecha_registro":"2026-06-12"
}
### Adicionar Producto
POST http://api.asistenciasexto/productos
Content-Type: application/json

{
  "codBarras":"750105531021",
  "descripcion":"Arroz Integral 2kg",
  "stock":50,
  "precio_unitario":12.51,
  "fecha_registro":"2026-06-12"
}

### Eliminar Producto
DELETE http://api.asistenciasexto/productos/29
